packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  # React
  react: 19.2.4
  react-dom: 19.2.4

  # TypeScript
  typescript: 5.9.3
  '@types/react': 19.2.14
  '@types/react-dom': 19.2.3
  '@types/node': 24.10.13

  # PandaCSS
  '@pandacss/dev': 1.8.2

  # Storybook
  storybook: 10.2.8
  '@storybook/addon-docs': 10.2.8

  # Vite
  vite: 7.3.1
  vite-tsconfig-paths: 6.1.1
  '@vitejs/plugin-react': 5.1.4

  # UI Libraries
  '@floating-ui/react': 0.27.18
  motion: 12.34.0

  # Testing
  vitest: 4.0.18
  '@vitest/browser': 4.0.18
  '@vitest/browser-playwright': 4.0.18
  playwright: 1.57.0
