packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  # React
  react: 19.2.3
  react-dom: 19.2.3

  # TypeScript
  typescript: 5.9.3
  '@types/react': 19.2.9
  '@types/react-dom': 19.2.3
  '@types/node': 24.10.9

  # PandaCSS
  '@pandacss/dev': 1.8.1

  # Storybook
  storybook: 10.1.11
  '@storybook/addon-docs': 10.1.11

  # Vite
  vite: 7.3.1
  vite-tsconfig-paths: 6.0.4
  '@vitejs/plugin-react': 5.1.2

  # UI Libraries
  '@floating-ui/react': 0.27.16
  motion: 12.24.12

  # Testing
  vitest: 4.0.17
  '@vitest/browser': 4.0.17
  '@vitest/browser-playwright': 4.0.17
  playwright: 1.57.0
