packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  # React
  react: 19.2.4
  react-dom: 19.2.4

  # TypeScript
  typescript: 5.9.3
  '@types/react': 19.2.13
  '@types/react-dom': 19.2.3
  '@types/node': 24.10.12

  # PandaCSS
  '@pandacss/dev': 1.8.1

  # Storybook
  storybook: 10.2.7
  '@storybook/addon-docs': 10.2.7

  # Vite
  vite: 7.3.1
  vite-tsconfig-paths: 6.0.5
  '@vitejs/plugin-react': 5.1.3

  # UI Libraries
  '@floating-ui/react': 0.27.17
  motion: 12.34.0

  # Testing
  vitest: 4.0.18
  '@vitest/browser': 4.0.18
  '@vitest/browser-playwright': 4.0.18
  playwright: 1.57.0
