classDiagram
  class ユーザー {
    名前
    チャレンジ
    価値観
    隠された正体
    実績
    テスト結果
  }
  class ミッション {
    名前
    説明
    期限日
  }
  class クエスト {
    名前
    説明

    消化する()
    新規追加()
    編集する()
    削除する()
  }
  class 悪者との戦い {
    名前
    説明 

    消化する()
    新規追加()
    編集する()
    削除する()
  }
  class パワーアップアイテム {
    名前
    説明 

    消化する()
    新規追加()
    編集する()
    削除する()
  }
  class エピックウィン {
    名前
    説明 

    消化する()
    新規追加()
    編集する()
    削除する()
  }


  ユーザー "1" -- "*" クエスト
  ユーザー "1" -- "*" パワーアップアイテム
  ユーザー "1" -- "*" 悪者との戦い
  ユーザー "1" -- "*" エピックウィン
